name = "ashish-portfolio-mcp"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[alias]
"ai" = "./shims/ai.ts"

[durable_objects]
bindings = [
  { name = "MCP_OBJECT", class_name = "PortfolioMCP" }
]

[[kv_namespaces]]
binding = "VISITORS"
id = "471a4e9deb7f495b8a91c26b1682be4c"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PortfolioMCP"]
